import { useState } from 'react';
import {
  Plus,
  Trash2,
  FileText,
  Eye,
  Copy,
  Check,
} from 'lucide-react';
import {
  Card,
  CardHeader,
  CardTitle,
  Button,
  Badge,
  Modal,
  Input,
  TextArea,
  Select,
} from '../components/common';
import { useStore } from '../store';
import { SESSION_ROLES, STAGES, GATE_REQUIREMENTS } from '../types';
import type { Document, DocumentType, SessionRole } from '../types';

export function Documents() {
  const {
    currentProjectId,
    projects,
    getProjectDocuments,
    getProjectHypotheses,
    getProjectExperiments,
    getProjectPRDs,
    getProjectMetrics,
    createDocument,
    updateDocument,
    deleteDocument,
  } = useStore();

  const currentProject = projects.find((p) => p.id === currentProjectId);
  const documents = currentProjectId ? getProjectDocuments(currentProjectId) : [];
  const hypotheses = currentProjectId ? getProjectHypotheses(currentProjectId) : [];
  const experiments = currentProjectId ? getProjectExperiments(currentProjectId) : [];
  const prds = currentProjectId ? getProjectPRDs(currentProjectId) : [];
  const metrics = currentProjectId ? getProjectMetrics(currentProjectId) : [];

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);
  const [selectedDocument, setSelectedDocument] = useState<Document | null>(null);
  const [copied, setCopied] = useState(false);

  const [formData, setFormData] = useState({
    type: 'one_pager' as DocumentType,
    title: '',
    targetRole: undefined as SessionRole | undefined,
  });

  if (!currentProject) {
    return (
      <div className="flex flex-col items-center justify-center h-96">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          事業案を選択してください
        </h2>
        <p className="text-gray-500 mb-6">
          サイドバーから事業案を選択してください
        </p>
      </div>
    );
  }

  const generateOnePager = (): string => {
    const currentStage = STAGES.find((s) => s.id === currentProject.stage);
    const prd = prds[0];
    const unverifiedHypotheses = hypotheses.filter((h) => h.status === 'unverified');
    const completedExperiments = experiments.filter((e) => e.status === 'completed');

    return `# ${currentProject.name}

## 1-Pager Summary

### Idea
${currentProject.description}

### Problem
${prd?.why.problem || '（PRDで定義してください）'}

### Solution
${prd?.what.solution || '（PRDで定義してください）'}

### Target Customer
${prd?.why.targetCustomer || '（PRDで定義してください）'}

### Market
- ステージ: ${currentStage?.name} (${currentStage?.description})
- 検証済み仮説: ${hypotheses.filter((h) => h.status === 'validated').length}件
- 完了実験: ${completedExperiments.length}件

### Business Model
${prd?.what.solution || '（事業計画で定義してください）'}

### Risks
${prd?.risks.map((r) => `- ${r.description}`).join('\n') || '（PRDで定義してください）'}

### Next Steps
${unverifiedHypotheses.slice(0, 3).map((h) => `- ${h.title}の検証`).join('\n') || '- 次の仮説を立てる'}

---
Generated by VPoP Agent
`;
  };

  const generateBusinessPlan = (): string => {
    const currentStage = STAGES.find((s) => s.id === currentProject.stage);
    const gateRequirements = GATE_REQUIREMENTS.find((g) => g.stage === currentProject.stage);
    const prd = prds[0];
    const nsmMetric = metrics.find((m) => m.type === 'NSM');

    return `# ${currentProject.name} 事業計画

## エグゼクティブサマリー
${currentProject.description}

## 現在のステージ
**${currentStage?.name}**: ${currentStage?.description}

## ビジョン・ミッション
### Vision
${prd?.core.vision || '（PRDで定義してください）'}

### Mission
${prd?.core.mission || '（PRDで定義してください）'}

## 課題と解決策
### 課題
${prd?.why.problem || '（PRDで定義してください）'}

### ターゲット顧客
${prd?.why.targetCustomer || '（PRDで定義してください）'}

### 解決策
${prd?.what.solution || '（PRDで定義してください）'}

## 主要指標
### North Star Metric
${nsmMetric ? `**${nsmMetric.name}**: ${nsmMetric.currentValue || '-'} ${nsmMetric.unit} (目標: ${nsmMetric.targetValue || '-'} ${nsmMetric.unit})` : '（NSMを設定してください）'}

### KPI
${metrics.filter((m) => m.type === 'KPI').map((m) => `- ${m.name}: ${m.currentValue || '-'} ${m.unit}`).join('\n') || '（KPIを設定してください）'}

## 仮説と検証状況
### 検証済み仮説
${hypotheses.filter((h) => h.status === 'validated').map((h) => `- ${h.title}`).join('\n') || '（まだありません）'}

### 未検証仮説
${hypotheses.filter((h) => h.status === 'unverified').map((h) => `- ${h.title}`).join('\n') || '（まだありません）'}

## 実験結果
${experiments.filter((e) => e.status === 'completed').map((e) => `### ${e.title}
- 目的: ${e.objective}
- 結果: ${e.results || '（記録なし）'}
- 学び: ${e.learnings || '（記録なし）'}
`).join('\n') || '（完了した実験はありません）'}

## リスクと対策
${prd?.risks.map((r) => `### ${r.description}
- 影響度: ${r.impact}
- 発生確率: ${r.probability}
- 対策: ${r.mitigation}
`).join('\n') || '（PRDで定義してください）'}

## ゲート条件（${currentStage?.name}）
### 必要な提出物
${gateRequirements?.deliverables.map((d) => `- [ ] ${d}`).join('\n') || '（未定義）'}

### 必要な根拠
${gateRequirements?.evidenceRequired.map((e) => `- [ ] ${e}`).join('\n') || '（未定義）'}

---
Generated by VPoP Agent
`;
  };

  const generateSessionBrief = (role: SessionRole): string => {
    const roleConfig = SESSION_ROLES.find((r) => r.id === role);
    const currentStage = STAGES.find((s) => s.id === currentProject.stage);
    const prd = prds[0];
    const nsmMetric = metrics.find((m) => m.type === 'NSM');

    return `# ${role}壁打ち用ブリーフ

## 事業案: ${currentProject.name}
**ステージ**: ${currentStage?.name} (${currentStage?.description})

## ${role}の関心事項
${roleConfig?.focus}

## 事前共有事項

### 現在の状況
- 検証済み仮説: ${hypotheses.filter((h) => h.status === 'validated').length}件
- 未検証仮説: ${hypotheses.filter((h) => h.status === 'unverified').length}件
- 完了実験: ${experiments.filter((e) => e.status === 'completed').length}件

### 主要指標
${nsmMetric ? `- NSM (${nsmMetric.name}): ${nsmMetric.currentValue || '-'} ${nsmMetric.unit}` : ''}
${metrics.filter((m) => m.type === 'KPI').slice(0, 3).map((m) => `- ${m.name}: ${m.currentValue || '-'} ${m.unit}`).join('\n')}

## 論点（${role}向け）
${roleConfig?.questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

## 想定される質問と回答準備

${role === 'CEO' ? `### 戦略整合性について
${prd?.core.vision || '（PRDで定義してください）'}

### 勝ち筋について
（準備してください）

### 撤退条件について
（準備してください）
` : ''}

${role === 'CFO' ? `### 投資対効果について
（準備してください）

### 損益分岐点について
（準備してください）

### 資金使途について
（準備してください）
` : ''}

${role === 'COO' ? `### 運用体制について
（準備してください）

### 品質管理について
（準備してください）
` : ''}

${role === 'CSO' ? `### 競争優位性について
（準備してください）

### 市場構造について
（準備してください）
` : ''}

${role === 'CPO' ? `### プロダクト戦略整合について
${prd?.core.vision || '（PRDで定義してください）'}

### 顧客価値と事業価値の一貫性について
${prd?.why.value || '（PRDで定義してください）'}
` : ''}

## リスク認識
${prd?.risks.slice(0, 3).map((r) => `- ${r.description} (影響: ${r.impact}, 確率: ${r.probability})`).join('\n') || '（PRDで定義してください）'}

---
Generated by VPoP Agent
`;
  };

  const generateContent = (type: DocumentType, role?: SessionRole): string => {
    switch (type) {
      case 'one_pager':
        return generateOnePager();
      case 'business_plan':
        return generateBusinessPlan();
      case 'session_brief':
        return role ? generateSessionBrief(role) : '';
      case 'prd':
        const prd = prds[0];
        return prd ? JSON.stringify(prd, null, 2) : '（PRDを作成してください）';
      default:
        return '';
    }
  };

  const handleCreate = () => {
    if (!formData.title.trim()) return;

    const content = generateContent(formData.type, formData.targetRole);

    createDocument({
      projectId: currentProjectId!,
      type: formData.type,
      title: formData.title,
      content,
      targetRole: formData.targetRole,
      version: 1,
      status: 'draft',
    });

    setIsModalOpen(false);
    setFormData({
      type: 'one_pager',
      title: '',
      targetRole: undefined,
    });
  };

  const handleDelete = (id: string) => {
    if (window.confirm('このドキュメントを削除しますか？')) {
      deleteDocument(id);
    }
  };

  const openPreview = (doc: Document) => {
    setSelectedDocument(doc);
    setIsPreviewOpen(true);
  };

  const copyToClipboard = async (content: string) => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getTypeBadge = (type: DocumentType) => {
    switch (type) {
      case 'one_pager':
        return <Badge variant="info" size="sm">1-Pager</Badge>;
      case 'prd':
        return <Badge variant="success" size="sm">PRD</Badge>;
      case 'business_plan':
        return <Badge variant="warning" size="sm">事業計画</Badge>;
      case 'session_brief':
        return <Badge size="sm">壁打ちブリーフ</Badge>;
    }
  };

  const getStatusBadge = (status: Document['status']) => {
    switch (status) {
      case 'draft':
        return <Badge size="sm">下書き</Badge>;
      case 'review':
        return <Badge variant="warning" size="sm">レビュー中</Badge>;
      case 'final':
        return <Badge variant="success" size="sm">最終版</Badge>;
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">成果物</h1>
          <p className="text-sm text-gray-500 mt-1">
            1-Pager、事業計画、壁打ちブリーフなどの成果物を生成・管理
          </p>
        </div>
        <Button onClick={() => setIsModalOpen(true)}>
          <Plus className="w-4 h-4 mr-2" />
          成果物を生成
        </Button>
      </div>

      {/* Quick Generate */}
      <Card>
        <CardHeader>
          <CardTitle>クイック生成</CardTitle>
        </CardHeader>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <Button
            variant="secondary"
            className="h-auto py-4 flex-col"
            onClick={() => {
              setFormData({ type: 'one_pager', title: `${currentProject.name} 1-Pager`, targetRole: undefined });
              setIsModalOpen(true);
            }}
          >
            <FileText className="w-6 h-6 mb-2" />
            <span>1-Pager</span>
          </Button>
          <Button
            variant="secondary"
            className="h-auto py-4 flex-col"
            onClick={() => {
              setFormData({ type: 'business_plan', title: `${currentProject.name} 事業計画`, targetRole: undefined });
              setIsModalOpen(true);
            }}
          >
            <FileText className="w-6 h-6 mb-2" />
            <span>事業計画</span>
          </Button>
          <Button
            variant="secondary"
            className="h-auto py-4 flex-col"
            onClick={() => {
              setFormData({ type: 'session_brief', title: `CFO壁打ちブリーフ`, targetRole: 'CFO' });
              setIsModalOpen(true);
            }}
          >
            <FileText className="w-6 h-6 mb-2" />
            <span>CFOブリーフ</span>
          </Button>
          <Button
            variant="secondary"
            className="h-auto py-4 flex-col"
            onClick={() => {
              setFormData({ type: 'session_brief', title: `CEO壁打ちブリーフ`, targetRole: 'CEO' });
              setIsModalOpen(true);
            }}
          >
            <FileText className="w-6 h-6 mb-2" />
            <span>CEOブリーフ</span>
          </Button>
        </div>
      </Card>

      {/* Document List */}
      {documents.length === 0 ? (
        <Card>
          <div className="text-center py-12">
            <FileText className="w-12 h-12 text-gray-300 mx-auto mb-4" />
            <p className="text-gray-500 mb-4">まだ成果物がありません</p>
            <p className="text-sm text-gray-400">
              上のクイック生成ボタンから成果物を作成してください
            </p>
          </div>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {documents.map((doc) => (
            <Card key={doc.id}>
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <FileText className="w-5 h-5 text-blue-500" />
                    <h4 className="font-medium text-gray-900">{doc.title}</h4>
                  </div>
                  <div className="flex gap-2 mb-2">
                    {getTypeBadge(doc.type)}
                    {getStatusBadge(doc.status)}
                    {doc.targetRole && (
                      <Badge size="sm">{doc.targetRole}向け</Badge>
                    )}
                  </div>
                  <p className="text-xs text-gray-500">
                    v{doc.version} | 更新: {new Date(doc.updatedAt).toLocaleDateString()}
                  </p>
                </div>
                <div className="flex items-center gap-1">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => openPreview(doc)}
                    title="プレビュー"
                  >
                    <Eye className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => copyToClipboard(doc.content)}
                    title="コピー"
                  >
                    {copied ? (
                      <Check className="w-4 h-4 text-green-500" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleDelete(doc.id)}
                    title="削除"
                  >
                    <Trash2 className="w-4 h-4 text-red-500" />
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* Create Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="成果物を生成"
      >
        <div className="space-y-4">
          <Select
            label="種類"
            value={formData.type}
            onChange={(e) => setFormData({ ...formData, type: e.target.value as DocumentType })}
            options={[
              { value: 'one_pager', label: '1-Pager' },
              { value: 'business_plan', label: '事業計画' },
              { value: 'session_brief', label: '壁打ちブリーフ' },
            ]}
          />

          {formData.type === 'session_brief' && (
            <Select
              label="対象の壁打ち相手"
              value={formData.targetRole || ''}
              onChange={(e) => setFormData({ ...formData, targetRole: e.target.value as SessionRole })}
              options={[
                { value: '', label: '選択してください...' },
                ...SESSION_ROLES.map((r) => ({ value: r.id, label: `${r.name} - ${r.focus}` })),
              ]}
            />
          )}

          <Input
            label="タイトル"
            placeholder="成果物のタイトル..."
            value={formData.title}
            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
          />

          <div className="p-4 bg-blue-50 rounded-lg">
            <p className="text-sm text-blue-600">
              成果物は、現在の事業案データ（仮説、実験、PRD、指標など）を
              もとに自動生成されます。生成後に編集することも可能です。
            </p>
          </div>

          <div className="flex justify-end gap-3 pt-4">
            <Button variant="secondary" onClick={() => setIsModalOpen(false)}>
              キャンセル
            </Button>
            <Button onClick={handleCreate}>生成</Button>
          </div>
        </div>
      </Modal>

      {/* Preview Modal */}
      <Modal
        isOpen={isPreviewOpen}
        onClose={() => setIsPreviewOpen(false)}
        title={selectedDocument?.title || ''}
        size="xl"
      >
        {selectedDocument && (
          <div className="space-y-4">
            <div className="flex justify-end gap-2">
              <Button
                variant="secondary"
                size="sm"
                onClick={() => copyToClipboard(selectedDocument.content)}
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4 mr-1" />
                    コピー済み
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 mr-1" />
                    コピー
                  </>
                )}
              </Button>
            </div>
            <div className="prose prose-sm max-w-none bg-gray-50 p-6 rounded-lg overflow-auto max-h-[60vh]">
              <pre className="whitespace-pre-wrap text-sm text-gray-700">
                {selectedDocument.content}
              </pre>
            </div>
            <TextArea
              label="編集"
              rows={10}
              value={selectedDocument.content}
              onChange={(e) => {
                updateDocument(selectedDocument.id, {
                  content: e.target.value,
                  version: selectedDocument.version + 1,
                });
                setSelectedDocument({
                  ...selectedDocument,
                  content: e.target.value,
                });
              }}
            />
          </div>
        )}
      </Modal>
    </div>
  );
}
